import html
import json
import os
import re
import urllib.error
import urllib.request
from datetime import datetime, timezone
from urllib.parse import urlparse

from mcp.server.fastmcp import FastMCP


MAX_TITLE_LENGTH = 200
MAX_BODY_LENGTH = 20_000
EMAIL_PATTERN = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")

server = FastMCP("mailing")


def require_environment() -> tuple[str, list[str], str]:
    mailing_url = os.environ.get("MAILING_URL", "")
    parsed_url = urlparse(mailing_url)
    if (
        parsed_url.scheme != "https"
        or not parsed_url.hostname
        or parsed_url.username
        or parsed_url.password
    ):
        raise RuntimeError("MAILING_URL must be a valid HTTPS URL")

    recipients = [
        recipient.strip()
        for recipient in os.environ.get("REPORT_RECIPIENTS", "").split(",")
        if recipient.strip()
    ]
    if not recipients or any(not EMAIL_PATTERN.fullmatch(recipient) for recipient in recipients):
        raise RuntimeError("REPORT_RECIPIENTS must contain valid email addresses")

    workflow_run_url = os.environ.get("WORKFLOW_RUN_URL", "")
    parsed_workflow_url = urlparse(workflow_run_url)
    if parsed_workflow_url.scheme != "https" or parsed_workflow_url.hostname != "github.com":
        raise RuntimeError("WORKFLOW_RUN_URL must be a valid github.com URL")

    return mailing_url, recipients, workflow_run_url


def create_payload(title: str, body: str, recipients: list[str], workflow_run_url: str) -> bytes:
    title = title.strip()
    body = body.strip()
    if not title or len(title) > MAX_TITLE_LENGTH:
        raise ValueError(f"title must contain 1-{MAX_TITLE_LENGTH} characters")
    if not body or len(body) > MAX_BODY_LENGTH:
        raise ValueError(f"body must contain 1-{MAX_BODY_LENGTH} characters")

    escaped_body = html.escape(body).replace("\n", "<br>\n")
    email_body = (
        '<html><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #24292f;">'
        f"<h1>{html.escape(title)}</h1>"
        f"<p>{escaped_body}</p>"
        '<hr style="border: 0; border-top: 1px solid #d0d7de;">'
        f'<p>Generated by <a href="{html.escape(workflow_run_url, quote=True)}">GitHub Actions</a>.</p>'
        "</body></html>"
    )
    payload = {
        "title": title,
        "timeFrame": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "body": email_body,
        "workflowRunUrl": workflow_run_url,
        "recipients": recipients,
    }
    return json.dumps(payload).encode("utf-8")


@server.tool()
def send_email(title: str, body: str) -> str:
    """Send a plain-text issue triage report to the configured recipients."""
    mailing_url, recipients, workflow_run_url = require_environment()
    request = urllib.request.Request(
        mailing_url,
        data=create_payload(title, body, recipients, workflow_run_url),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            if not 200 <= response.status < 300:
                raise RuntimeError(f"mailing endpoint returned HTTP {response.status}")
    except urllib.error.HTTPError as error:
        raise RuntimeError(f"mailing endpoint returned HTTP {error.code}") from None
    except urllib.error.URLError:
        raise RuntimeError("mailing endpoint is unavailable") from None

    return "Email sent successfully."


if __name__ == "__main__":
    server.run(transport="stdio")
