name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - main
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-9247-Tool
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: Agent job 1
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                fetchTags: true
              - task: NodeTool@0
                displayName: Use Node 20.x
                inputs:
                  versionSpec: 20.x
              - task: Npm@1
                displayName: npm install
                inputs:
                  verbose: false
              - task: CmdLine@2
                displayName: Command Line Script
                inputs:
                  script: npx @vscode/vsce@latest package
              - task: CopyFiles@2
                displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
                inputs:
                  Contents: "*.vsix"
                  TargetFolder: $(Build.ArtifactStagingDirectory)
