name: Take snapshot of open issues
on: 
  schedule: 
    - cron: '0 8 1 * *'
  workflow_dispatch:
jobs:
  dump_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Take issue snapshot
        run: |
          gh issue list -R $GITHUB_REPOSITORY --limit 1000 --search "is:issue is:open sort:reactions-+1-desc" --json number,url,reactionGroups,title,labels > $REPO.$(date +"%Y-%m-%d").json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.name }}
      - name: Save artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./*.json
          retention-days: 1
      - name: Log in to Azure
        uses: azure/login@f5d393ae46f8fde4be8b75f32e3fc50e654ad0ca # v3.0.1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      - name: Upload to Azure
        uses: azure/CLI@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode login -d ${{ vars.AZURE_STORAGE_CONTAINER_NAME }} -s .
